version: '3.7'

services:
  gdrive-migrator:
    image: pfidr/rclone:1.63.0
    container_name: gdrive-migrator
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ${LOCAL_FS}:${LOCAL_FS}:shared
    environment:
      SYNC_SRC: "gdrive:"
      SYNC_DEST: ${LOCAL_FS}
      SYNC_OPTS: '--log-level ${LOG_LEVEL} --check-first --order-by size,descending  --stats 5m --use-mmap --timeout 2m --config /config/rclone.conf --max-duration=${MAX_DURATION} --max-transfer ${MAX_TRANSFER} --bwlimit ${BWLIMIT} --drive-skip-gdocs --drive-acknowledge-abuse --cutoff-mode SOFT --fast-list --drive-server-side-across-configs --drive-stop-on-download-limit'
      RCLONE_DIR_CHECK_SKIP: 'false'
      RCLONE_CMD: copy
      FORCE_SYNC: ${FORCE_SYNC}
      TZ: ${DOCKER_TZ}
      CRON: ${RCLONE_CRON}
      UID: ${PUID}
      GID: ${PGID}
      CHECK_URL: ${CHECK_URL}
      HC_LOG: ${HC_LOG}
      OUTPUT_LOG: ${OUTPUT_LOG}
      ROTATE_LOG: ${ROTATE_LOG}


  rclone-sa-autoswap:
    image: dantebarba/rclone-sa-autoswap:latest
    container_name: rclone-sa-autoswap
    volumes:
      - ./config:/config
    environment:
      CRON: ${AUTOSWAP_CRON} # will renew the SA number once every hour
      MAX_NUMBER: ${SA_NUMBER} # the number of SAs you generated
      PREFIX: ${SA_PREFIX} # the prefix with path included before the SA Number.
      # SAs should be named with the following schema: my-sa-{number}.json where number is the SA designated number.
      # this number should be sequential, from 1 to n.