version: '3.7'

services:
  gdrive-migrator:
    image: pfidr/rclone:1.56.2
    container_name: gdrive-migrator
    restart: unless-stopped
    volumes:
      - ./:/config
    environment:
      SYNC_SRC: "old-gdrive:"
      SYNC_DEST: "new-gdrive:"
      SYNC_OPTS: '--log-level ${LOG_LEVEL} --stats 120s --buffer-size 128M --drive-chunk-size 128M --use-mmap --timeout 1m --config /config/rclone.conf --max-duration=${MAX_DURATION} --min-size=${MIN_SIZE} --max-size=${MAX_SIZE} --drive-server-side-across-configs --drive-stop-on-upload-limit --drive-stop-on-download-limit'
      RCLONE_DIR_CHECK_SKIP: 'false'
      RCLONE_CMD: copy
      FORCE_SYNC: 'true'
      TZ: ${DOCKER_TZ}
      CRON: "0 * * * *"
      UID: ${PUID}
      GID: ${PGID}

  rclone-sa-autoswap:
    image: dantebarba/rclone-sa-autoswap:latest
    container_name: rclone-sa-autoswap
    volumes:
      - ./:/config
    environment:
      CRON: ${AUTOSWAP_CRON} # will renew the SA number once every hour
      MAX_NUMBER: ${SA_NUMBER} # the number of SAs you generated
      PREFIX: ${SA_PREFIX} # the prefix with path included before the SA Number.
      # SAs should be named with the following schema: my-sa-{number}.json where number is the SA designated number.
      # this number should be sequential, from 1 to n.